name: Run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Selecciona el ambiente donde correr los tests"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - produccion

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instala dependencias
        run: npm ci

      - name: Corre Cypress en Chrome
        run: echo "Ejecutando en ambiente: ${{ github.event.inputs.environment }}"
          ENVIRONMENT=${{ github.event.inputs.environment }} npm run test:clean:chrome

      - name: Subir reporte de pruebas
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-mochawesome-report
          path: cypress/reports/
