name: Run Cypress Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Seleccionar entorno"
        required: true
        default: "produ"
        type: choice
        options:
          - staging
          - produ

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    env:
      # 🔹 Variables del entorno elegidas por el usuario
      USER_ID_1: ${{ secrets.USER_ID_1 }}
      USER_NAME_1: ${{ secrets.USER_NAME_1 }}
      USER_EMAIL_1: ${{ secrets.USER_EMAIL_1 }}
      USER_AVATAR_1: ${{ secrets.USER_AVATAR_1 }}
      USER_TOKEN_1: ${{ secrets.USER_TOKEN_1 }}
      IS_AUTHENTICATED: ${{ secrets.IS_AUTHENTICATED }}
      WAS_ON_BOARDED: ${{ secrets.WAS_ON_BOARDED }}
      BASE_URL: ${{ secrets.BASE_URL_PRODU }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run --browser chrome
